# Fedora Kickstart headless 
# https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#chapter-1-introduction


autopart --encrypted --passphrase SiriSvartKatt
clearpart --all
eula --agreed
firewall --enable --ssh
reboot
keyboard se
lang sv_SE.UTF-8
network --onboot --bootproto dhcp --hostname fedora-laptop
rootpw --lock
selinux --enforcing
ssh key --username figge "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAINmpUj7taHkVd9xCmuQ3agnFgW67MxUdf2taaSplQM0iAAAAEXNzaDpmZWRvcmEtbGFwdG9w figge@laptop"
timezone --utc Europe/Stockholm
user --name figge --password $y$j9T$pvd56X5xERkijmM2j9eNY.$izy/w/YuL2s4uqQdide.AJ7ki1gEhoEzH0Re/ss/ky.

%packages
@admin-tools
@editors
@fonts
@gnome-desktop
#@games
#@graphical-internet
#@graphics
@hardware-support
@input-methods
#@java
#@office
#@online-docs
#@printing
@sound-and-video
@text-internet
#@base-x
#xfsprogs
mtools
#gpgme
#openoffice.org-opensymbol-fonts
#gvfs-obexftp
#hdparm
#gok
#iok
#vorbis-tools
#jack-audio-connection-kit
#ncftp
gdm
%end

# Reboot after installation
reboot
