rpmfusion_fedora_version: 44
rpmfusion_packages:
  - intel-media-driver
  - libva-nvidia-driver
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-plugins-ugly
  - libavcodec-freeworld
  - libheif-freeworld
  - motion
