---
# https://codeberg.org/danielfm/ansible-collections-workstation/src/branch/main/roles/gnome/tasks
# GNOME

- name: Ensure dconf packages are installed
  become: true
  ansible.builtin.dnf:
    state: present
    name:
      - dconf
      - python3-psutil
  tags:
    - pkg

- name: Install desktop packages
  ansible.builtin.dnf:
    name: "{{ gnome_packages }}"
    state: present

- name: Install fonts
  ansible.builtin.dnf:
    name: "{{ gnome_fonts }}"
    state: present
