## Controllers

# Internal controllers
allow id 1d6b:0002 serial "0000:00:14.0" name "xHCI Host Controller" hash "jEP/6WzviqdJ5VSeTUY8PatCNBKeaREvo2OqdplND/o=" parent-hash "rV9bfLq7c2eA4tYjVjwO4bxhm+y6GgZpl9J60L0fBkY=" with-interface 09:00:00 with-connect-type ""
allow id 1d6b:0003 serial "0000:00:14.0" name "xHCI Host Controller" hash "E8Zs26CP5+JQoiPVmDSuTb4j11VatW+WHlWxiX8+qJc=" parent-hash "rV9bfLq7c2eA4tYjVjwO4bxhm+y6GgZpl9J60L0fBkY=" with-interface 09:00:00 with-connect-type ""
allow id 1d6b:0002 serial "0000:39:00.0" name "xHCI Host Controller" hash "9fK3PDPVp4DJyi9OBhr0VqxziSVqv1/vZeNFDVsjXIM=" parent-hash "90stQELLrv0Na+ItxLC3raVX5pL4Qhf2264/jKNE/GA=" with-interface 09:00:00 with-connect-type ""
allow id 1d6b:0003 serial "0000:39:00.0" name "xHCI Host Controller" hash "WKDlBlXSIgFsdjhJj04N5hTzeUmN4zmXBpWB5nMZ+ik=" parent-hash "90stQELLrv0Na+ItxLC3raVX5pL4Qhf2264/jKNE/GA=" with-interface 09:00:00 with-connect-type ""

# External usb-c display hub with two usb-b ports.
allow id 2109:2817 serial "000000000" name "USB2.0 Hub             " hash "rLGjB76Wg6d9x2Oxg0vyHWVxRovP0DzF9EF0fu3+U9I=" parent-hash "jEP/6WzviqdJ5VSeTUY8PatCNBKeaREvo2OqdplND/o=" with-interface { 09:00:01 09:00:02 } with-connect-type "hotplug"

## devices

# internal Fingerprint 
allow id 27c6:533c serial "" name "FingerPrint" hash "h9vvNvpAnOV54vaHZhlYO+HMSjiuY0QzEDt0opOphZU=" parent-hash "jEP/6WzviqdJ5VSeTUY8PatCNBKeaREvo2OqdplND/o=" via-port "1-10" with-interface ff:00:00 with-connect-type "not used"

# internal Webcam
allow id 0c45:672e serial "" name "Integrated_Webcam_HD" hash "0FnwqInuozAt1lx5xXHVKEld1BOMtjYenkLsbW9iQ3U=" parent-hash "jEP/6WzviqdJ5VSeTUY8PatCNBKeaREvo2OqdplND/o=" via-port "1-11" with-interface { 0e:01:00 0e:02:00 0e:02:00 0e:02:00 0e:02:00 0e:02:00 0e:02:00 0e:02:00 0e:01:00 0e:02:00 0e:02:00 0e:02:00 0e:02:00 0e:02:00 0e:02:00 0e:02:00 } with-connect-type "not used"

# internal Bluetooth 
allow id 8087:0026 serial "" name "" hash "Z5csNGxiUukPPZwSHPyUqpVCNagsfOSSNL2CfXhw4IY=" parent-hash "jEP/6WzviqdJ5VSeTUY8PatCNBKeaREvo2OqdplND/o=" via-port "1-14" with-interface { e0:01:01 e0:01:01 e0:01:01 e0:01:01 e0:01:01 e0:01:01 e0:01:01 e0:01:01 } with-connect-type "hardwired"



# Logitech mouse usb-b, can only be connected to external display hub. 
allow id 046d:c547 serial "" name "USB Receiver" hash "gFx7kcPo3OnfDcPhrJk3PxeBiF1o6/JGeTevInhob4A=" with-interface { 03:01:02 03:01:01 03:00:00 } with-connect-type "unknown"

# Ethernet usb-b, can only be connected to external display hub.
allow id 0bda:8153 serial "000001" name "USB 10/100/1000 LAN" hash "0e64v7j3WdPYy2m8WjI5GBk9ubTiB153rAwHzsCn57c=" with-interface { ff:ff:00 02:06:00 0a:00:00 0a:00:00 } with-connect-type "unknown"

# FIDO2 usb-c security keys. Can only be connected to internal controllers, ports 1-4,5 
# Serial is not detected, preferably I want to allow only my specific keys. 
allow id 1ea8:f829 serial "" name "Security Key(F829)" hash "KjhQB8ZRtigF4fqt6QX4pUXiSIZ3a4+7+ZLa1s/Ykso=" with-interface { 03:00:00 0b:00:00 } with-connect-type "hotplug"

