---
- name: Configure Fedora workstation
  hosts: workstation
  become: true

  vars_files:
    - vars.yml

  roles:
    - base
#   - security
    - gnome
#   - rpmfusion
    - flatpak
    - vscode
    - virtualization
