---
workstation_user: figge

packages:
  - fzf
  - ripgrep
  - rsync
  - neovim
  - kitty
  - zsh
  - git
  - htop
  - btop
  - bubblewrap
  - iotop
  - nmap
  - arp-scan
  - wireshark

vscode_extensions:
  - redhat.ansible

flatpaks:
  - org.strawberrymusicplayer.strawberry
  - de.haeckerfelix.Shortwave
  - org.videolan.VLC

fonts:
  - adobe-source-code-pro-fonts
  - adobe-source-sans-pro-fonts
  - adobe-source-serif-pro-fonts
  - dejavu-fonts-all
  - fira-code-fonts
  - google-noto-fonts-common
  - google-roboto-fonts
  - ibm-plex-mono-fonts
  - jetbrains-mono-fonts
  - redhat-display-fonts
  - redhat-mono-fonts
  - redhat-text-fonts

gnome_color_scheme: prefer-dark
# Accent color: 'blue', 'teal', 'green', 'yellow', 'orange', 'red', 'pink', 'purple', 'slate'
gnome_accent_color: blue

require_secure_boot: true
require_tpm: true
require_luks: true
ssh_server_enabled: false

# default, security
dnf_automatic_upgrade_type: security

