---
flatpak_packages:
  - org.strawberrymusicplayer.strawberry
  - de.haeckerfelix.Shortwave
  - org.videolan.VLC
  - com.mattjakeman.ExtensionManager
  - io.mpv.Mpv
  - io.github.mrvladus.List
  - io.gitlab.news_flash.NewsFlash
  - io.gitlab.adhami3310.Converter
  - io.gitlab.adhami3310.Impression
  - de.wwwtech.gitte
  - app.fotema.Fotema
  - app.drey.Dialect
  - com.spotify.Client
  - com.github.tchx84.Flatseal
  - com.mattjakeman.ExtensionManager
  - com.usebruno.Bruno
  - com.github.qarmin.czkawka
  - com.rafaelmardojai.Blanket
  - de.haeckerfelix.Fragments
  - dev.geopjr.Tuba
  - dev.geopjr.Collision
  - im.riot.Riot
  - io.missioncenter.MissionCenter
  - io.dbeaver.DBeaverCommunity
  - net.nokyan.Resources
  - net.trowell.typesetter
  - net.waterfox.waterfox
  - org.mozilla.firefox
  - org.gimp.GIMP
  - org.gnome.SoundRecorder
  - org.libreoffice.LibreOffice
  - org.signal.Signal
  - org.keepassxc.KeePassXC
  - org.gnome.World.PikaBackup
  - org.gaphor.Gaphor
  - org.pgadmin.pgadmin4
  - org.gnome.Builder
  - org.gnome.design.Contrast
  - org.gustavoperedo.FontDownloader
  - re.sonny.Junction
